### PR TITLE
Add HipChat notification

### PR DESCRIPTION
**Pull request by williamlord**

### CODE REVIEW

**Comment by williamlord** [comment]
Hi @wurzeldub,

I'm just consolidating another fork of this repository so I can delete it, it contained this HipChat feature by @bflynnwonga.

It seems the source code and the package are owned by different parties, are you OK if we share the collaboration/responsibility on this? We can add you to this repository with write access, and are you able to make https://rubygems.org/profiles/wongatech an owner on the Gem as well?

Also I will protect the master branch and enforce reviews on it.

Let me know what you think.

Thanks,
William

**Comment by wurzeldub** [comment]
Sounds cool to me William

**Comment by williamlord** [comment]
Perfect thanks, sent you invite @wurzeldub.

**Comment by williamlord** [comment]
Hi @wurzeldub, are you able to add https://rubygems.org/profiles/wongatech as another owner on the Gem?

**Comment by williamlord** [comment]
http://help.rubygems.org/discussions/problems/30275-ownership-of-rubyjobbuilderdsl-gem/

**Pull request merged**
